
*  lam va tai len github
* chia nhom (max 5 ng) va lam hai bai nhom(45-45)
* co 6 bai ca nhan, chon 1 bai cham diem va 5
bai cong diem





In [2]:
import numpy as np
import pandas as pd


In [ ]:
#cau 1 & 2: all - any
arr = np.random.randint(21 , size=(3,3))
print("random array:\n",arr)

all_nonzero= np.all(arr!=0)
print("Tat ca cac phan tu khac 0",all_nonzero)

any_nonzero= np.any(arr!=0)
print("Co phan tu khac 0?",any_nonzero)

random array:
 [[12  5  3]
 [19  6  6]
 [17 10 10]]
Tat ca cac phan tu khac 0 True
Co phan tu khac 0? True


In [ ]:
#cau 3: ss 2 mang
a1= np.array([1,5,10])
a2= np.array([1,2,12])

print("So sanh mang 1 chieu:")
print("Greater(a>b):\n",np.greater(a1,a2))
print("Greater_equal(a>=b):\n",np.greater_equal(a1,a2))

b1= np.array([[1,2], [3,4]])
b2= np.array([[1,1], [4,4]])

print("So sanh mang 2 chieu:")
print("Less(a<b):\n",np.less(b1,b2))
print("Less_equal(a<=b):\n",np.less_equal(b1,b2))

So sanh mang 1 chieu:
Greater(a>b):
 [False  True False]
Greater_equal(a>=b):
 [ True  True False]
So sanh mang 2 chieu:
Less(a<b):
 [[False False]
 [ True False]]
Less_equal(a<=b):
 [[ True False]
 [ True  True]]


In [ ]:
#cau 4: tao mang 1 so
a= np.ones(10)
b=np.zeros(10)
c= np.ones(10)*5
d = np.full(10, 5)

print(a)
print(b)
print(c)
print(d)

result= np.concatenate((a,b,c))
print("Ket qua:",result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
Ket qua: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
#cau 5: tao mang so chan tu [30, 70]
even_arr= np.arange(30, 71, 2)

print("mang chan: ",even_arr)

mang chan:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#cau 6: ma tran don vi
identity_matrix= np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#cau 7: cat mang
arr= np.random.randint(15, 56, size=10)
print(arr)

print("in cac ngoai dau va cuoi:", arr[1:-1])

[20 30 45 50 47 19 34 28 39 51]
in cac ngoai dau va cuoi: [30 45 50 47 19 34 28 39]


In [ ]:
# cau 8: doi dau theo DK
arr = np.random.randint(0, 21, size=20)
print(arr)

arr[(arr >=9) & (arr<=15)] *= -1
print(arr)

[ 7  6 17 10 17 12 17 10  8  2 17 15 13  0 13  2  3  7  1 14]
[  7   6  17 -10  17 -12  17 -10   8   2  17 -15 -13   0 -13   2   3   7
   1 -14]


In [ ]:
#cau 9: tao ma tran ngau nhien
arr= np.random.random((3,4))
print(arr)

In [ ]:
#cau 10: ma tran co vien
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#cau 11: ham np.diag
diag_matrix= np.diag([1,2,3,4,5])
print(diag_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
#cau 12:Tinh tong trong mang(3x3x3)
arr= np.random.randint(1,10, size=(3,3,3))
print(arr)
print("Tong cac phan tu trong mang:",np.sum(arr))

sum_rows = np.sum(arr, axis=1)
print("Tong cac phan tu trong tung dong:",sum_rows)

sum_cols = np.sum(arr, axis=2)
print("Tong cac phan tu trong tung cot:",sum_cols)

[[[4 9 2]
  [5 6 4]
  [7 9 6]]

 [[2 8 8]
  [4 3 6]
  [3 7 4]]

 [[4 3 9]
  [7 5 8]
  [8 4 3]]]
Tong cac phan tu trong mang: 148
Tong cac phan tu trong tung dong: [[16 24 12]
 [ 9 18 18]
 [19 12 20]]
Tong cac phan tu trong tung cot: [[15 15 22]
 [18 13 14]
 [16 20 15]]


In [ ]:
#Câu 13: Tạo 2 vector ngẫu nhiên 10 phần tử.
#Thực hiện inner product (tích vô hướng) bằng np.dot
vector1 = np.random.rand(10)
vector2 = np.random.rand(10)

print("Vector 1:\n", vector1)
print("Vector 2:\n", vector2)

# Thực hiện inner product (tích vô hướng) bằng np.dot
inner_product = np.dot(vector1, vector2)

print("\nInner product (tích vô hướng):", inner_product)

In [ ]:
# Câu 14: Tạo ma trận A = 4x3 và vector y gồm 3 phần tử ngẫu nhiên.
#Thêm vector y vào từng dòng của ma trận A.
matrix_A = np.random.randint(0, 10, size=(4, 3))
print("Ma trận A gốc:\n", matrix_A)

vector_y = np.random.randint(0, 5, size=3)
print("\nVector y:\n", vector_y)

# Thêm vector y vào từng dòng của ma trận A (sử dụng broadcasting)
result_matrix = matrix_A + vector_y

print("\nMa trận sau khi thêm vector y vào mỗi dòng:\n", result_matrix)

In [ ]:
# Câu 15: Viết chương trình Pandas để cộng, trừ, nhân, chia
#2 Series: [2, 4, 6, 8, 10] và [1, 3, 5, 7, 10].
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", series1)
print("\nSeries 2:\n", series2)

# Cộng hai Series
addition = series1 + series2
print("\nCộng:\n", addition)

# Trừ hai Series
subtraction = series1 - series2
print("\nTrừ:\n", subtraction)

# Nhân hai Series
multiplication = series1 * series2
print("\nNhân:\n", multiplication)

# Chia hai Series (xử lý trường hợp chia cho 0 nếu có)
division = series1 / series2
print("\nChia:\n", division)

### Câu 16: Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series.

Trong Pandas, thuộc tính `.ix` đã bị loại bỏ (deprecated) từ phiên bản 0.20.0 và hoàn toàn không còn trong các phiên bản mới hơn. Thay vào đó, chúng ta nên sử dụng `.iloc` (dựa trên vị trí số nguyên) hoặc `.loc` (dựa trên nhãn) để truy cập dữ liệu.

Để chuyển đổi cột đầu tiên của DataFrame thành Series, chúng ta có thể sử dụng `.iloc[:, 0]` hoặc truy cập trực tiếp bằng tên cột nếu có.

In [20]:
# Tạo một DataFrame mẫu
data = {'Col_A': [10, 20, 30, 40],
        'Col_B': [1, 2, 3, 4],
        'Col_C': ['X', 'Y', 'Z', 'W']}
df = pd.DataFrame(data)

print("DataFrame gốc:\n", df)

# Chuyển đổi cột đầu tiên ('Col_A') thành Series bằng .iloc
# .iloc[:, 0] chọn tất cả các hàng và cột thứ 0 (cột đầu tiên)
first_column_as_series_iloc = df.iloc[:, 0]

print("\nCột đầu tiên thành Series (sử dụng .iloc):\n", first_column_as_series_iloc)
print("Loại của kết quả: ", type(first_column_as_series_iloc))

# Hoặc chuyển đổi bằng cách truy cập trực tiếp tên cột (nếu biết tên cột)
first_column_as_series_name = df['Col_A']
print("\nCột đầu tiên thành Series (sử dụng tên cột):\n", first_column_as_series_name)
print("Loại của kết quả: ", type(first_column_as_series_name))

DataFrame gốc:
    Col_A  Col_B Col_C
0     10      1     X
1     20      2     Y
2     30      3     Z
3     40      4     W

Cột đầu tiên thành Series (sử dụng .iloc):
 0    10
1    20
2    30
3    40
Name: Col_A, dtype: int64
Loại của kết quả:  <class 'pandas.core.series.Series'>

Cột đầu tiên thành Series (sử dụng tên cột):
 0    10
1    20
2    30
3    40
Name: Col_A, dtype: int64
Loại của kết quả:  <class 'pandas.core.series.Series'>


In [21]:
# Câu 17: Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên.
df_cau17 = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=['Cot_A', 'Cot_B', 'Cot_C'])
print("DataFrame gốc:\n", df_cau17)

# Sắp xếp DataFrame theo cột 'Cot_A' (mặc định là tăng dần)
df_sorted_A = df_cau17.sort_values(by='Cot_A')
print("\nDataFrame sắp xếp theo Cot_A (tăng dần):\n", df_sorted_A)

# Sắp xếp DataFrame theo cột 'Cot_B' giảm dần
df_sorted_B_desc = df_cau17.sort_values(by='Cot_B', ascending=False)
print("\nDataFrame sắp xếp theo Cot_B (giảm dần):\n", df_sorted_B_desc)

DataFrame gốc:
    Cot_A  Cot_B  Cot_C
0     22     26     77
1     74     93     93
2     42     95     79
3     48     40     14

DataFrame sắp xếp theo Cot_A (tăng dần):
    Cot_A  Cot_B  Cot_C
0     22     26     77
2     42     95     79
3     48     40     14
1     74     93     93

DataFrame sắp xếp theo Cot_B (giảm dần):
    Cot_A  Cot_B  Cot_C
2     42     95     79
1     74     93     93
3     48     40     14
0     22     26     77


In [22]:
# Câu 18: Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex).
series_cau18 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series gốc:\n", series_cau18)

# Định nghĩa index mới
new_index = ['e', 'b', 'a', 'f']

# Thay đổi index của Series bằng reindex
series_reindexed = series_cau18.reindex(new_index)
print("\nSeries sau khi reindex:\n", series_reindexed)

# Lưu ý: Các phần tử có index mới không tồn tại trong Series gốc sẽ có giá trị NaN.

Series gốc:
 a    10
b    20
c    30
d    40
dtype: int64

Series sau khi reindex:
 e     NaN
b    20.0
a    10.0
f     NaN
dtype: float64


In [23]:
# Câu 19: Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (dùng hàm isin của pandas).
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("Series sr1:\n", sr1)
print("\nSeries sr2:\n", sr2)

# Tìm các phần tử trong sr1 mà không có trong sr2
elements_not_in_sr2 = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:\n", elements_not_in_sr2)

Series sr1:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Series sr2:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
 0    1
2    3
4    5
dtype: int64


In [24]:
# Câu 20: Tìm hiểu phép toán numpy.union1d, numpy.intersect1d (hội, giao)
# và viết chương trình minh họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử.
series_x = pd.Series(np.random.randint(0, 50, size=20))
series_y = pd.Series(np.random.randint(25, 75, size=20))

print("Series X:\n", series_x)
print("\nSeries Y:\n", series_y)

# Chuyển đổi Series sang mảng NumPy để sử dụng các hàm của NumPy
arr_x = series_x.values
arr_y = series_y.values

# Thực hiện phép hợp (union) bằng numpy.union1d
union_result = np.union1d(arr_x, arr_y)
print("\nKết quả phép hợp (Union of X and Y):\n", union_result)

# Thực hiện phép giao (intersection) bằng numpy.intersect1d
intersect_result = np.intersect1d(arr_x, arr_y)
print("\nKết quả phép giao (Intersection of X and Y):\n", intersect_result)

Series X:
 0      3
1     43
2     42
3     33
4     26
5     32
6     48
7     29
8     26
9     22
10     3
11    14
12    19
13    47
14     5
15    19
16     3
17    34
18    14
19    46
dtype: int64

Series Y:
 0     28
1     45
2     73
3     42
4     39
5     39
6     56
7     47
8     48
9     30
10    65
11    27
12    25
13    48
14    41
15    39
16    49
17    28
18    34
19    39
dtype: int64

Kết quả phép hợp (Union of X and Y):
 [ 3  5 14 19 22 25 26 27 28 29 30 32 33 34 39 41 42 43 45 46 47 48 49 56
 65 73]

Kết quả phép giao (Intersection of X and Y):
 [34 42 47 48]


In [25]:
#Câu 21: Viết chương trình Pandas thêm Series y vào Series x theo chiều dọc (vertical),
# chiều ngang (horizontal) (Tìm hiểu hàm append và concat của pandas).
# Tạo Series x
series_x = pd.Series(np.arange(10))
print("Series x:\n", series_x)

# Tạo Series y
series_y = pd.Series(list('pqrstuvwxy'))
print("\nSeries y:\n", series_y)

# Thêm series y vào series x theo chiều dọc (vertical)
# Sử dụng pd.concat với axis=0 (mặc định) hoặc .append (đã bị deprecated trong các phiên bản mới của Pandas)
vertical_concat = pd.concat([series_x, series_y], axis=0)
print("\nKết quả nối theo chiều dọc (vertical):\n", vertical_concat)

# Thêm series y vào series x theo chiều ngang (horizontal)
# Sử dụng pd.concat với axis=1
horizontal_concat = pd.concat([series_x, series_y], axis=1)
print("\nKết quả nối theo chiều ngang (horizontal):\n", horizontal_concat)

Series x:
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Series y:
 0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết quả nối theo chiều dọc (vertical):
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết quả nối theo chiều ngang (horizontal):
    0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [26]:
#Câu 22: Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_exam = pd.DataFrame(exam_data, index=labels)
print("DataFrame 'df_exam':\n", df_exam)

DataFrame 'df_exam':
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [27]:
#Câu 23: Từ bài 22, cho biết 3 dòng đầu tiên.
print("3 dòng đầu tiên của DataFrame:\n", df_exam.head(3))

3 dòng đầu tiên của DataFrame:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [28]:
#Câu 24: Từ bài 22, chọn cột ‘name’ và ‘score’.
print("Cột 'name' và 'score':\n", df_exam[['name', 'score']])

Cột 'name' và 'score':
         name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [29]:
#Câu 25: Từ bài 22, chọn những dòng có attempts > 2.
print("Những dòng có 'attempts' > 2:\n", df_exam[df_exam['attempts'] > 2])

Những dòng có 'attempts' > 2:
       name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [30]:
#Câu 26: Từ bài 22, cho biết số dòng, số cột của DataFrame.
num_rows, num_cols = df_exam.shape
print(f"Số dòng của DataFrame: {num_rows}")
print(f"Số cột của DataFrame: {num_cols}")

Số dòng của DataFrame: 10
Số cột của DataFrame: 4


In [31]:
#Câu 27: Từ bài 22, cho biết những dòng có score là NaN (tìm hiểu hàm isnull của pandas).
print("Những dòng có 'score' là NaN:\n", df_exam[df_exam['score'].isnull()])

Những dòng có 'score' là NaN:
     name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [32]:
#Câu 28: Từ bài 22, cho biết những dòng có score trong khoảng (15, 20) (tìm hiểu hàm between của pandas).
print("Những dòng có 'score' trong khoảng (15, 20):\n", df_exam[df_exam['score'].between(15, 20)])

Những dòng có 'score' trong khoảng (15, 20):
         name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [33]:
#Câu 29: Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20).
print("Những dòng có 'attempt' > 2 và 'score' trong khoảng (15, 20):\n", \
      df_exam[(df_exam['attempts'] > 2) & (df_exam['score'].between(15, 20))])

Những dòng có 'attempt' > 2 và 'score' trong khoảng (15, 20):
       name  score  attempts qualify
f  Michael   20.0         3     yes


In [34]:
#Câu 30: Từ bài 22, thay đổi giá trị dòng ‘d’, cột score là 19 (tìm hiểu hàm loc của pandas).
print("DataFrame gốc trước khi thay đổi:\n", df_exam)

# Thay đổi giá trị dòng 'd', cột 'score' thành 19 bằng .loc
df_exam.loc['d', 'score'] = 19

print("\nDataFrame sau khi thay đổi (dòng 'd', cột 'score' là 19):\n", df_exam)

DataFrame gốc trước khi thay đổi:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

DataFrame sau khi thay đổi (dòng 'd', cột 'score' là 19):
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
