In [2]:
import numpy as np
import tensorflow as tf

### 1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [6]:
tensor_zeros_2x3 = tf.zeros([2, 3])
print(tensor_zeros_2x3)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### 2. Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được gán 0

In [7]:
X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
tensor_zeros_like_X = tf.zeros_like(X)
print("Original X:\n", X)
print("Tensor of zeros like X:\n", tensor_zeros_like_X)

Original X:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor of zeros like X:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


### 3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [8]:
tensor_fives_3x2 = tf.fill([3, 2], 5)
print(tensor_fives_3x2)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


### 4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [9]:
# The only even numbers in the range [5, 10] are 6, 8, 10.
# Creating 50 distinct even elements within this small range is not possible.
# I will interpret this as creating a tensor with 50 even numbers starting from 6.
even_elements_tensor = tf.range(start=6, limit=6 + 2 * 50, delta=2)
print(even_elements_tensor)
print("Shape:", even_elements_tensor.shape)

tf.Tensor(
[  6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40
  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
  78  80  82  84  86  88  90  92  94  96  98 100 102 104], shape=(50,), dtype=int32)
Shape: (50,)


### 5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]

In [10]:
tensor_range_10_100 = tf.range(start=10, limit=101, delta=2)
print(tensor_range_10_100)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


### 6. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0, standard deviation = 2

In [11]:
random_normal_tensor = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print(random_normal_tensor)

tf.Tensor(
[[-1.6361638  -0.7958024 ]
 [ 0.47206908  0.09535098]
 [-3.22376     3.0950541 ]], shape=(3, 2), dtype=float32)


### 7. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi [0, 2]

In [12]:
random_uniform_tensor = tf.random.uniform(shape=[3, 2], minval=0.0, maxval=2.0)
print(random_uniform_tensor)

tf.Tensor(
[[0.20409751 1.2910469 ]
 [1.2624664  0.91986394]
 [1.782615   1.4505548 ]], shape=(3, 2), dtype=float32)


### 8. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng random_shuffle)

In [13]:
X_to_shuffle = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.int32)
shuffled_X = tf.random.shuffle(X_to_shuffle)
print("Original X:\n", X_to_shuffle)
print("Shuffled X:\n", shuffled_X)

Original X:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shuffled X:
 tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


### 9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử dụng random_crop)

In [14]:
original_image_tensor = tf.random.uniform(shape=[10, 10, 3], minval=0, maxval=256, dtype=tf.int32)
cropped_tensor = tf.image.random_crop(original_image_tensor, size=[5, 5, 3])
print("Original tensor shape:", original_image_tensor.shape)
print("Cropped tensor shape:", cropped_tensor.shape)
print("Cropped tensor (first few values):\n", cropped_tensor[0,0,:])

Original tensor shape: (10, 10, 3)
Cropped tensor shape: (5, 5, 3)
Cropped tensor (first few values):
 tf.Tensor([ 23 207 240], shape=(3,), dtype=int32)


### 10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y (element-wise)

In [15]:
x = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.float32)
y = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.float32)

result_tensor = tf.where(tf.less(x, y), x + y, x - y)

print("x:", x)
print("y:", y)
print("Result (x+y if x<y, else x-y):", result_tensor)

x: tf.Tensor([2.100923  5.023682  7.6064835 1.5600085 7.1137953], shape=(5,), dtype=float32)
y: tf.Tensor([7.789178  9.0582    7.018285  5.5608597 7.409079 ], shape=(5,), dtype=float32)
Result (x+y if x<y, else x-y): tf.Tensor([ 9.8901005  14.081882    0.58819866  7.120868   14.522875  ], shape=(5,), dtype=float32)


### 11. Tạo ngẫu nhiên 2 tensor kích thước x = (3, 2) và giá trị trong khoảng [5, 10], y = (2, 3) và giá trị [15, 20] tương ứng. Hãy giữ giá trị đường chéo của x và thực hiện x + y.

In [16]:
x_tensor = tf.random.uniform(shape=[3, 2], minval=5, maxval=11, dtype=tf.int32)
y_tensor = tf.random.uniform(shape=[2, 3], minval=15, maxval=21, dtype=tf.int32)

print("x_tensor:\n", x_tensor)
print("y_tensor:\n", y_tensor)

# Get the main diagonal elements of x_tensor
diagonal_x = tf.linalg.diag_part(x_tensor)
print("Diagonal of x_tensor:", diagonal_x)

# Note: x_tensor (3, 2) and y_tensor (2, 3) have incompatible shapes for element-wise addition (x + y).
# If you intended matrix multiplication, you would use tf.matmul(x_tensor, y_tensor).
# tf.matmul(x_tensor, y_tensor) would result in a (3, 3) tensor.
# If you meant to add a diagonal matrix created from diagonal_x to y_tensor, that would also require reshaping/padding.
# Direct addition as requested is not possible with the given shapes.

x_tensor:
 tf.Tensor(
[[6 9]
 [6 6]
 [8 8]], shape=(3, 2), dtype=int32)
y_tensor:
 tf.Tensor(
[[20 20 15]
 [18 16 17]], shape=(2, 3), dtype=int32)
Diagonal of x_tensor: tf.Tensor([6 6], shape=(2,), dtype=int32)


### 12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng, trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.

In [17]:
# Create two random tensors
x = tf.random.uniform(shape=[3, 2, 2], minval=0, maxval=10, dtype=tf.float32)
y = tf.random.uniform(shape=[3, 2, 2], minval=0, maxval=10, dtype=tf.float32)

print("Tensor x:\n", x)
print("Tensor y:\n", y)

# Define arithmetic operations as TensorFlow functions
@tf.function
def add_tensors(t1, t2):
  return tf.add(t1, t2)

@tf.function
def subtract_tensors(t1, t2):
  return tf.subtract(t1, t2)

@tf.function
def multiply_tensors(t1, t2):
  return tf.multiply(t1, t2)

@tf.function
def divide_tensors(t1, t2):
  # Add a small epsilon to avoid division by zero
  return tf.divide(t1, t2 + tf.keras.backend.epsilon())

# Perform operations using the graph functions
sum_tensor = add_tensors(x, y)
diff_tensor = subtract_tensors(x, y)
prod_tensor = multiply_tensors(x, y)
div_tensor = divide_tensors(x, y)

print("\nSum (x + y):\n", sum_tensor)
print("\nDifference (x - y):\n", diff_tensor)
print("\nProduct (x * y):\n", prod_tensor)
print("\nDivision (x / y):\n", div_tensor)

Tensor x:
 tf.Tensor(
[[[4.4672117  6.435672  ]
  [5.251664   7.488285  ]]

 [[8.493351   3.6647832 ]
  [2.0993447  9.28495   ]]

 [[0.02159953 4.5351386 ]
  [9.549527   0.5616975 ]]], shape=(3, 2, 2), dtype=float32)
Tensor y:
 tf.Tensor(
[[[4.6321225  7.047088  ]
  [7.5410104  0.43317318]]

 [[3.6547709  1.5869796 ]
  [8.1155405  2.1862042 ]]

 [[8.354858   6.9188404 ]
  [3.1183803  3.6320722 ]]], shape=(3, 2, 2), dtype=float32)

Sum (x + y):
 tf.Tensor(
[[[ 9.099335  13.482759 ]
  [12.792675   7.9214582]]

 [[12.148122   5.251763 ]
  [10.214886  11.471154 ]]

 [[ 8.376458  11.4539795]
  [12.667908   4.1937695]]], shape=(3, 2, 2), dtype=float32)

Difference (x - y):
 tf.Tensor(
[[[-0.1649108  -0.61141634]
  [-2.2893462   7.055112  ]]

 [[ 4.83858     2.0778036 ]
  [-6.016196    7.0987463 ]]

 [[-8.333259   -2.3837018 ]
  [ 6.4311466  -3.0703747 ]]], shape=(3, 2, 2), dtype=float32)

Product (x * y):
 tf.Tensor(
[[[20.692673   45.352745  ]
  [39.602856    3.2437243 ]]

 [[31.041252    5

### 13. Xây dựng model để tính tổng hai tensor x, y

In [18]:
class SumModel(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

  @tf.function
  def __call__(self, x, y):
    return tf.add(x, y)

# Create an instance of the model
sum_model = SumModel()

# Generate new random tensors for demonstration
x_model_sum = tf.random.uniform(shape=[2, 2], minval=0, maxval=5, dtype=tf.float32)
y_model_sum = tf.random.uniform(shape=[2, 2], minval=0, maxval=5, dtype=tf.float32)

print("x for sum model:\n", x_model_sum)
print("y for sum model:\n", y_model_sum)
print("Sum from model:\n", sum_model(x_model_sum, y_model_sum))

x for sum model:
 tf.Tensor(
[[2.863441  1.5393752]
 [3.5012114 3.9562213]], shape=(2, 2), dtype=float32)
y for sum model:
 tf.Tensor(
[[3.4481978 1.9218808]
 [3.6741269 2.2585368]], shape=(2, 2), dtype=float32)
Sum from model:
 tf.Tensor(
[[6.311639  3.461256 ]
 [7.1753383 6.214758 ]], shape=(2, 2), dtype=float32)


### 14. Xây dựng model để tính hiệu và tích hai tensor x, y

In [19]:
class DiffProdModel(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

  @tf.function
  def calculate(self, x, y):
    difference = tf.subtract(x, y)
    product = tf.multiply(x, y)
    return difference, product

# Create an instance of the model
diff_prod_model = DiffProdModel()

# Generate new random tensors for demonstration
x_model_diff_prod = tf.random.uniform(shape=[2, 2], minval=5, maxval=10, dtype=tf.float32)
y_model_diff_prod = tf.random.uniform(shape=[2, 2], minval=0, maxval=5, dtype=tf.float32)

print("x for diff/prod model:\n", x_model_diff_prod)
print("y for diff/prod model:\n", y_model_diff_prod)

difference_result, product_result = diff_prod_model.calculate(x_model_diff_prod, y_model_diff_prod)
print("\nDifference from model:\n", difference_result)
print("\nProduct from model:\n", product_result)

x for diff/prod model:
 tf.Tensor(
[[8.96236   8.621416 ]
 [5.7597084 5.429287 ]], shape=(2, 2), dtype=float32)
y for diff/prod model:
 tf.Tensor(
[[0.893479   1.1880761 ]
 [4.148243   0.07226169]], shape=(2, 2), dtype=float32)

Difference from model:
 tf.Tensor(
[[8.068881  7.43334  ]
 [1.6114655 5.357025 ]], shape=(2, 2), dtype=float32)

Product from model:
 tf.Tensor(
[[ 8.007681   10.242899  ]
 [23.89267     0.39232945]], shape=(2, 2), dtype=float32)


### 15. Xây dựng model để tính chu vi hình chữ nhật P = (a +b) * 2

In [20]:
class RectanglePerimeterModel(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

  @tf.function
  def calculate_perimeter(self, a, b):
    # Ensure a and b are treated as TensorFlow tensors
    a = tf.cast(a, tf.float32)
    b = tf.cast(b, tf.float32)
    perimeter = tf.multiply(tf.add(a, b), 2.0)
    return perimeter

# Create an instance of the model
perimeter_model = RectanglePerimeterModel()

# Example usage
length = tf.constant(10.0)
width = tf.constant(5.0)

perimeter = perimeter_model.calculate_perimeter(length, width)
print(f"Length (a): {length.numpy()}, Width (b): {width.numpy()}")
print(f"Perimeter P = (a + b) * 2: {perimeter.numpy()}")

# Another example with different values
length_2 = 7.5
width_2 = 3.2
perimeter_2 = perimeter_model.calculate_perimeter(length_2, width_2)
print(f"\nLength (a): {length_2}, Width (b): {width_2}")
print(f"Perimeter P = (a + b) * 2: {perimeter_2.numpy()}")

Length (a): 10.0, Width (b): 5.0
Perimeter P = (a + b) * 2: 30.0

Length (a): 7.5, Width (b): 3.2
Perimeter P = (a + b) * 2: 21.399999618530273


16.Xây dựng model để tính diện tích toàn phần hình hộp chữ nhật

In [22]:
def model_dien_tich_hinh_hop(a, b, c):
    # Chuyển đổi đầu vào thành tensor float32
    a = tf.cast(a, tf.float32)
    b = tf.cast(b, tf.float32)
    c = tf.cast(c, tf.float32)

    # S_xq = (a + b) * c * 2
    s_xq = tf.multiply(tf.add(a, b), tf.multiply(c, 2.0))

    # S_tp = (a * b) * 2 + S_xq
    s_tp = tf.add(tf.multiply(tf.multiply(a, b), 2.0), s_xq)

    return s_tp

# Test thử
print(f"Diện tích toàn phần: {model_dien_tich_hinh_hop(5, 3, 4).numpy()}")

Diện tích toàn phần: 94.0


17. Xây dựng model chứng minh hai cạnh bên hình thang song song theo điều kiện:Điều kiện: $AD // BC \iff (AD = BC \text{ và } AB = CD)$

In [23]:
def model_chung_minh_song_song(AD_val, BC_val, AB_val, CD_val):
    # Kiểm tra điều kiện AD = BC và AB = CD
    cond1 = tf.equal(AD_val, BC_val)
    cond2 = tf.equal(AB_val, CD_val)

    # Kết quả logic: AD // BC
    ad_parallel_bc = tf.logical_and(cond1, cond2)
    return ad_parallel_bc

# Test: Nếu AD=BC và AB=CD thì trả về True (AD // BC)
print(f"AD song song BC: {model_chung_minh_song_song(10, 10, 5, 5).numpy()}")

AD song song BC: True


18. Chứng minh hai cạnh đáy hình thang bằng nhauĐiều kiện: $AB = CD \iff (AD = BC \text{ và } AD // BC)$.

In [24]:
def model_chung_minh_day_bang_nhau(AD_len, BC_len, is_AD_parallel_BC):
    # Kiểm tra AD = BC
    cond1 = tf.equal(AD_len, BC_len)

    # Kết quả logic: AB = CD
    ab_equal_cd = tf.logical_and(cond1, is_AD_parallel_BC)
    return ab_equal_cd

# Test
print(f"AB bằng CD: {model_chung_minh_day_bang_nhau(10, 10, True).numpy()}")

AB bằng CD: True


19. Xây dựng model chứng minh NA = NC theo mô tả sau với AM, MB, AN, NC là đầu vào: Dựa trên mô tả: Nếu $MN // BC$ và $M$ là trung điểm $AB$ ($AM = MB$), thì $N$ là trung điểm $AC$ ($NA = NC$).

In [21]:
def model_chung_minh_trung_diem(AM, MB, is_MN_parallel_BC):
    """
    Input: AM, MB (độ dài), is_MN_parallel_BC (Boolean)
    Output: Boolean (Xác nhận NA = NC)
    """
    # Điều kiện 1: M là trung điểm AB
    is_M_midpoint = tf.equal(AM, MB)

    # Nếu M là trung điểm VÀ MN // BC thì N là trung điểm
    is_N_midpoint = tf.logical_and(is_M_midpoint, is_MN_parallel_BC)

    return is_N_midpoint

# Giả sử AM=5, MB=5 và MN song song BC
result = model_chung_minh_trung_diem(tf.constant(5), tf.constant(5), tf.constant(True))
print(f"Kết luận NA = NC: {result.numpy()}")

Kết luận NA = NC: True
